// Dependency-free regression checks. This sandbox never makes network requests.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map(),noop=()=>{},drawing=new Proxy({}, {get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)});
function element(id){if(!elements.has(id))elements.set(id,{id,value:'',dataset:{},style:{},hidden:false,disabled:false,textContent:'',listeners:{},classList:{set:new Set(),add(k){this.set.add(k)},remove(k){this.set.delete(k)},contains(k){return this.set.has(k)}},addEventListener(k,f){this.listeners[k]=f},querySelectorAll(){return []},getContext(){return drawing},getBoundingClientRect(){return {left:0,top:0,width:900,height:1200}},parentElement:{getBoundingClientRect(){return {width:900,height:1236}}},setPointerCapture:noop,hasPointerCapture:()=>false,click(){this.onclick?.()},toDataURL(){return 'data:image/webp;base64,AAAA'}});return elements.get(id)}
let archive=null,failStorage=false,fetches=0,response;
const box={document:{getElementById:element,querySelectorAll:()=>[],addEventListener:noop,createElement:()=>element('temp'),activeElement:null},crypto:require('node:crypto').webcrypto,matchMedia:()=>({matches:false,addEventListener:noop}),performance:{now:()=>0},setTimeout:()=>1,clearTimeout:noop,requestAnimationFrame:noop,devicePixelRatio:2,localStorage:{setItem(k,v){if(failStorage)throw Error('quota');archive=v},getItem:()=>archive},window:{addEventListener:noop},ResizeObserver:class{observe(){}},Image:class{set src(v){this.width=128;this.height=128;queueMicrotask(()=>this.onload())}},FileReader:class{readAsDataURL(){this.result='data:image/png;base64,AAAA';this.onload()}},Blob,URL,AbortController,console,confirm:()=>true,fetch:async()=>{fetches++;return response}};
vm.createContext(box);const source=fs.readFileSync('app.js','utf8').replace(/init\(\);\s*$/,'');vm.runInContext(source,box);const run=s=>vm.runInContext(s,box);
(async()=>{
run('scene=demo(); normalizeZ(); sync(); changed()');assert.equal(run('validate(scene).items.length'),9);assert.equal(JSON.parse(archive).schemaVersion,1);
run("selected=scene.items[0].id; scene.items[0].locked=true");const locked=run('JSON.stringify(current())');run("$('shuffle').onclick()");assert.equal(run('JSON.stringify(current())'),locked);assert.equal(run('scene.items.length'),9);run("$('undo').onclick()");assert.equal(run('scene.items[1].rotation'),-9);
run("$('addText').onclick(); $('text').listeners.focus(); $('text').value='中文\\nHELLO'; $('text').listeners.input(); $('text').listeners.blur()");assert.equal(run('current().text'),'中文\nHELLO');run("$('width').listeners.focus(); $('width').valueAsNumber=300; $('width').listeners.input(); $('width').listeners.blur()");assert.equal(run('current().height'),95);assert.equal(run('current().textBoxWidth'),600);run("$('undo').onclick()");assert.equal(run('current().width'),600);
const beforeDrag=run('history.length');run("selected=scene.items.at(-1).id; canvas.listeners.pointerdown({button:0,clientX:450,clientY:550,pointerId:1,preventDefault(){}}); canvas.listeners.pointermove({clientX:490,clientY:580}); canvas.listeners.pointermove({clientX:510,clientY:590}); canvas.listeners.pointerup({pointerId:1})");assert.equal(run('history.length'),beforeDrag+1);assert.equal(run('current().x'),510);run("$('undo').onclick()");assert.equal(run('current().x'),450);
run("for(let n=0;n<25;n++){checkpoint();scene.canvas.background=n%2?'#ffffff':'#eeeeee'}");assert.ok(run('history.length')>=20);
run("selected=scene.items.at(-1).id; current().rotation=37; const t=37*Math.PI/180; const p={x:current().x+20*Math.cos(t),y:current().y+20*Math.sin(t)}; globalThis.hit=local(p,current())");assert.ok(Math.abs(box.hit.x-20)<.001);assert.ok(Math.abs(box.hit.y)<.001);
run("current().x=-9999; current().y=-9999; keepVisible(current())");assert.ok(run('current().x')>-1800);
const saved=archive;failStorage=true;run("changed()");assert.equal(archive,saved);assert.ok(element('saveStatus').classList.contains('error'));failStorage=false;
const original=run('JSON.stringify(scene)');for(const patch of ["s.schemaVersion=2","s.items[0].width=Infinity","s.assets.bad={data:'blob:temporary',width:1,height:1}","s.items[0].id='__proto__'","s.items[0].animation='evil'","s.items[0].style.color='red'"]){assert.throws(()=>run(`{const s=clone(scene);${patch};validate(s)}`))}assert.equal(run('JSON.stringify(scene)'),original);
run("scene=validate(JSON.parse(JSON.stringify(scene)))");assert.deepEqual(JSON.parse(run('JSON.stringify(scene)')),JSON.parse(original));
await run("insertImage(new Blob(['image'],{type:'image/png'}))");assert.equal(run('Object.keys(scene.assets).length'),1);run("$('duplicate').onclick()");assert.equal(run('Object.keys(scene.assets).length'),1);assert.equal(run('scene.items.filter(i=>i.type===\'image\').length'),2);assert.ok(run("Object.values(scene.assets)[0].data.startsWith('data:image/')"));
run("selected=scene.items.at(-1).id;current().animation='float'");const initial=run('JSON.stringify(scene)');run('animation(current(),100);drawScene(ctx,100)');assert.equal(run('JSON.stringify(scene)'),initial);
const aiBefore=run('JSON.stringify(scene)');element('prompt').value='test';for(const fixture of [{ok:false,status:500,json:async()=>({error:'Internal server error'})},{ok:false,status:403},{ok:true,json:async()=>({error:'proxy failed'})},{ok:true,json:async()=>({status:'processing',output:['https://example.com/not-ready.png']})},{ok:true,json:async()=>({output:[]})}]){response=fixture;await run("$('generate').onclick()");assert.equal(run('JSON.stringify(scene)'),aiBefore);assert.equal(run('generating'),false)}assert.equal(fetches,5);
console.log('PASS: scene validation, Chinese/multiline edits, proportional resize, rotated hit coordinates, one undo per drag, 20+ history, locked Shuffle, storage failure preservation, JSON roundtrip, image asset deduplication, animation immutability, mocked HTTP/proxy/processing/empty-result failures. No network used.');
})().catch(e=>{console.error(e);process.exitCode=1});
